packages:
  - benchmarks
  - examples/css-in-js/*
  - examples/styled-components/*
  - packages/*

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0

onlyBuiltDependencies:
  - esbuild

strictPeerDependencies: false

publicHoistPattern:
  - '*prettier*'

syncInjectedDepsAfterScripts:
  - install
